services:
  # Backend API
  - type: web
    name: backend-finanzas-evan
    runtime: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/backend-finanzas.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: MAVEN_VERSION
        value: 3.9
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SHOW_SQL
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: APP_LOG_LEVEL
        value: INFO

  # Base de datos PostgreSQL
  - type: pgsql
    name: finanzas-db-evan
    databaseName: finanzas_evan
    user: finanzas_user
    plan: free